### PR TITLE
add phoenix contracts

### PR DESCRIPTION
**Pull request by mgpai22**

### CODE REVIEW

**Comment by Luivatra** [comment]
For repo I am thinking a relative path compared to the github in the organisation.
Also ideally the pr should come from that organisation to help verify, but guess we can ignore that on this one :)

**Comment by mgpai22** [comment]
so should I do 
```
"repo": "phoenix-hodlcoin-contracts/blob/main/hodlERG/contracts/proxy_contract/v1/ergoscript/phoenix_v1_hodlerg_proxy.es"
```

**Comment by Luivatra** [comment]
> so should I do
> 
> ```
> "repo": "phoenix-hodlcoin-contracts/blob/main/hodlERG/contracts/proxy_contract/v1/ergoscript/phoenix_v1_hodlerg_proxy.es"
> ```

yes exactly

**Comment by mgpai22** [comment]
@Luivatra fixed

**Comment by Luivatra** [comment]
perfect, just working on some validation workflow before I merge this.

**Pull request merged**
